<?php

namespace AppBundle\Repository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchBack($data)
    {
        $qb = $this->createQueryBuilder('e')
            ->leftJoin('e.city', 'ci')
            ->leftJoin('ci.country', 'co')
            ->orderBy('e.name', 'ASC');

        if (!empty($data['name'])) {
            $qb->andWhere('e.name like :name')
                ->setParameter('name', '%'.$data['name'].'%' );
        }
        if (!empty($data['city'])) {
            $qb->andWhere('ci.id = :city')
                ->setParameter('city', $data['city']);
        }
        if (!empty($data['country'])) {
            $qb->andWhere('c.id = :country')
                ->setParameter('country', $data['country']);
        }

        return $qb;
    }

    public function listByCity($data)
    {
        $qb = $this->createQueryBuilder('e')
            ->leftJoin('e.city', 'ci')
            ->where('ci.slug = :slug')
            ->setParameter('slug', $data)
            ->orderBy('e.name', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function listByCityId($data)
    {
        $qb = $this->createQueryBuilder('e')
            ->leftJoin('e.city', 'ci')
            ->where('ci.id = :id')
            ->setParameter('id', $data)
            ->orderBy('e.name', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
