<?php

namespace AppBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchBack($data)
    {
        $qb = $this->createQueryBuilder('e')
            ->leftJoin('e.country', 'c')->addSelect('c')
            ->orderBy('e.name', 'ASC');

        if (!empty($data['name'])) {
            $qb->andWhere('e.name like :name')
                ->setParameter('name', '%'.$data['name'].'%' );
        }
        if (!empty($data['country'])) {
            $qb->andWhere('c.id = :country')
                ->setParameter('country', $data['country']);
        }

        return $qb;
    }
}
