<?php

namespace AppBundle\Repository;

/**
 * MessageSentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageSentRepository extends \Doctrine\ORM\EntityRepository
{
}
