<?php

namespace AppBundle\Repository;

/**
 * MessageReceivedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageReceivedRepository extends \Doctrine\ORM\EntityRepository
{
}
