<?php

namespace AppBundle\Repository;

/**
 * PropertyFavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyFavoriteRepository extends \Doctrine\ORM\EntityRepository
{
    /*
 * Favorite list "to show them in profile, so for that we select images of travels"
 */
    public function listByUser($user)
    {
        $qb = $this->createQueryBuilder('e')
            ->leftJoin('e.property', 'p')->addSelect('p')
            ->leftJoin('p.category', 'c')->addSelect('c')
            ->leftJoin('p.image', 'i')->addSelect('i')
            ->where('e.user = '.$user)
            ->orderBy('e.id', 'DESC');

        return $qb;

    }
}
