<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function listBack($type)
    {
        $qb = $this->createQueryBuilder('e')
            ->leftJoin('e.area', 'ar')->addSelect('ar')
            ->leftJoin('ar.city', 'ci')->addSelect('ci')
            ->where('e.roles NOT LIKE :role')->setParameter('role', '%ROLE_ADMIN%')
            ->andWhere('e.roles NOT LIKE :role')->setParameter('role', '%ROLE_SUPER_ADMIN%')
            ->orderBy('e.id', 'DESC');

        if ($type == 'tous') {
            $qb->leftJoin('e.company', 'com')->addSelect('com');
            $qb->leftJoin('e.particular', 'par')->addSelect('par');
        } elseif ($type == 'entreprise') {
            $qb->innerJoin('e.company', 'com')->addSelect('com');
        } elseif ($type == 'particulier') {
            $qb->innerJoin('e.particular', 'par')->addSelect('par');
        } elseif ($type == 'disabled') {
            $qb->leftJoin('e.company', 'com')->addSelect('com');
            $qb->leftJoin('e.particular', 'par')->addSelect('par');
            $qb->andWhere('e.enabled = 0 ');
        }

        return $qb;
    }

    public function countUsers()
    {
        return $this->createQueryBuilder('u')
            ->select("count(u.id) as countUsers")
            ->getQuery()->getSingleResult();
    }

}
