front_office_app:
    resource: '@AppBundle/Controller/FrontOffice'
    type: annotation
    schemes: https

back_office_app:
    resource: '@AppBundle/Controller/BackOffice'
    type: annotation
    prefix: administration/
    schemes: https

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    schemes: https

#LiipImagineBundle
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"