back_message_sent_list:
    path:     /
    defaults: { _controller: AppBundle:BackOffice\MessageSentBack:list}

back_message_sent_show:
    path:     /show/{id}
    defaults: { _controller: AppBundle:BackOffice\MessageSentBack:show}
    options:
        expose: true

back_message_sent_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:BackOffice\MessageSentBack:delete}
    options:
        expose: true

back_message_sent_new:
    path:     /new
    defaults: { _controller: AppBundle:BackOffice\MessageSentBack:new}

