back_message_received_list:
    path:     /
    defaults: { _controller: AppBundle:BackOffice\MessageReceivedBack:list}

back_message_received_show:
    path:     /show/{id}
    defaults: { _controller: AppBundle:BackOffice\MessageReceivedBack:show}
    options:
        expose: true

back_message_received_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:BackOffice\MessageReceivedBack:delete}
    options:
        expose: true

